#!/usr/bin/env bats
#
# Tests for: WTA-002 - Configuration Namespace
# Feature: Consistent worktree.wt.* configuration namespace
# Requirements: R5.1-R5.3 from WTA-002/requirements.md
# Generated by: /mdt:tests
# Status: RED (implementation pending)
#

setup() {
    load 'test_helper/common-setup.bash'
    _common_setup
}

teardown() {
    if [[ -n "$TEST_REPO_DIR" && -d "$TEST_REPO_DIR" ]]; then
        cleanup_test_repo "$TEST_REPO_DIR"
    fi
    _common_teardown
}

# Feature: Configuration Namespace

@test "uses worktree.wt.defaultPath for path template" {
    # Given: repository with worktree.wt.defaultPath configured
    # When: user runs git wt 123
    # Then: worktree should exist at configured path

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    git_test config worktree.wt.defaultPath ".worktrees/{worktree_name}"

    run git_test wt 123 2>&1

    # Verify worktree exists at configured path
    git_test show-ref --verify --quiet "refs/heads/123"
    assert_dir_exists "$TEST_REPO_DIR/.worktrees/123"

    # Cleanup
    git_test worktree remove ".worktrees/123" 2>/dev/null || true
}

@test "worktree.wt.defaultPath takes precedence over old worktree.defaultPath" {
    # Given: repository with both old and new config set
    # When: user runs git wt 456
    # Then: worktree should use new namespace path

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    git_test config worktree.defaultPath ".old-worktrees/{worktree_name}"
    git_test config worktree.wt.defaultPath ".new-worktrees/{worktree_name}"

    run git_test wt 456 2>&1

    git_test show-ref --verify --quiet "refs/heads/456"
    assert_dir_exists "$TEST_REPO_DIR/.new-worktrees/456"
    refute_dir_exists "$TEST_REPO_DIR/.old-worktrees/456"

    # Cleanup
    git_test worktree remove ".new-worktrees/456" 2>/dev/null || true
}

@test "replaces {worktree_name} placeholder in path template" {
    # Given: repository with worktree.wt.defaultPath containing {worktree_name}
    # When: user runs git wt PROJ-789
    # Then: placeholder should be replaced with actual worktree name

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    git_test config worktree.wt.prefix "PROJ-"
    git_test config worktree.wt.defaultPath "wt/{worktree_name}"

    run git_test wt 789 2>&1

    git_test show-ref --verify --quiet "refs/heads/PROJ-789"
    assert_dir_exists "$TEST_REPO_DIR/wt/PROJ-789"

    # Cleanup
    git_test worktree remove "wt/PROJ-789" 2>/dev/null || true
}

@test "replaces {project_dir} placeholder in path template" {
    # Given: repository with worktree.wt.defaultPath containing {project_dir}
    # When: user runs git wt 999
    # Then: placeholder should be replaced with repository basename

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    REPO_NAME=$(basename "$TEST_REPO_DIR")
    git_test config worktree.wt.defaultPath "../wt/{project_dir}/{worktree_name}"

    run git_test wt 999 2>&1

    git_test show-ref --verify --quiet "refs/heads/999"
    assert_dir_exists "$TEST_REPO_DIR/../wt/$REPO_NAME/999"

    # Cleanup
    git_test worktree remove "../wt/$REPO_NAME/999" 2>/dev/null || true
}

@test "expands tilde in worktree.wt.defaultPath" {
    # Given: repository with worktree.wt.defaultPath containing tilde
    # When: user runs git wt 555
    # Then: tilde should expand to home directory

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    git_test config worktree.wt.defaultPath "~/worktrees/{worktree_name}"

    run git_test wt 555 2>&1

    git_test show-ref --verify --quiet "refs/heads/555"
    assert_dir_exists "$ISOLATED_GIT_HOME/worktrees/555"

    # Cleanup
    git_test worktree remove "$ISOLATED_GIT_HOME/worktrees/555" 2>/dev/null || true
}

@test "applies all worktree.wt.* configuration settings together" {
    # Given: repository with all worktree.wt.* settings configured
    # When: user runs git wt 42
    # Then: all settings should be applied

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    git_test config worktree.wt.prefix "TEST-"
    git_test config worktree.wt.zeroPadDigits 3
    git_test config worktree.wt.defaultPath ".custom-wt/{worktree_name}"

    run git_test wt 42 2>&1

    git_test show-ref --verify --quiet "refs/heads/TEST-042"
    assert_dir_exists "$TEST_REPO_DIR/.custom-wt/TEST-042"

    # Cleanup
    git_test worktree remove ".custom-wt/TEST-042" 2>/dev/null || true
}
