#!/usr/bin/env bats
#
# Tests for: WTA-002 - Consistent Behavior Across Commands
# Feature: git wt and git wt-rm handle input identically
# Requirements: R6.1-R6.3 from WTA-002/requirements.md
# Generated by: /mdt:tests
# Status: GREEN (implementation complete)
#

setup() {
    load 'test_helper/common-setup.bash'
    _common_setup
}

teardown() {
    if [[ -n "$TEST_REPO_DIR" && -d "$TEST_REPO_DIR" ]]; then
        cleanup_test_repo "$TEST_REPO_DIR"
    fi
    _common_teardown
}

# Feature: Consistent Behavior Across Commands

@test "wt and wt-rm use identical prefix logic" {
    # Given: repository with worktree.wt.prefix configured to "PROJ-"
    # When: user creates worktree with git wt 101
    # And: removes it with git wt-rm 101
    # Then: both commands should reference PROJ-101
    # And: worktree should be successfully removed

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    git_test config worktree.wt.prefix "PROJ-"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create with short input
    run git_test wt 101 2>&1
    git_test show-ref --verify --quiet "refs/heads/PROJ-101"

    # Remove with same short input
    run git_test wt-rm 101 <<< "y" 2>&1

    # Verify worktree was successfully removed
    assert_success
    assert_output --partial "Removed worktree"
    assert_output --partial "PROJ-101"
}

@test "wt-rm accepts full worktree name" {
    # Given: repository with worktree.wt.prefix configured to "PROJ-"
    # And: worktree created with git wt 101 (branch PROJ-101)
    # When: user runs git wt-rm PROJ-101
    # Then: worktree should be removed

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    git_test config worktree.wt.prefix "PROJ-"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create with short input
    run git_test wt 101 2>&1
    git_test show-ref --verify --quiet "refs/heads/PROJ-101"

    # Remove with full name
    run git_test wt-rm PROJ-101 <<< "y" 2>&1

    # Verify worktree was successfully removed
    assert_success
    assert_output --partial "Removed worktree"
    assert_output --partial "PROJ-101"
}

@test "wt and wt-rm use identical zero-padding logic" {
    # Given: repository with worktree.wt.zeroPadDigits configured to 4
    # And: worktree.wt.prefix configured to "ABC-"
    # When: user creates worktree with git wt 7
    # And: removes it with git wt-rm 7
    # Then: both commands should reference ABC-0007
    # And: worktree should be successfully removed

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    git_test config worktree.wt.prefix "ABC-"
    git_test config worktree.wt.zeroPadDigits 4
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create
    run git_test wt 7 2>&1
    git_test show-ref --verify --quiet "refs/heads/ABC-0007"

    # Remove
    run git_test wt-rm 7 <<< "y" 2>&1

    # Verify worktree was successfully removed
    assert_success
    assert_output --partial "Removed worktree"
    assert_output --partial "ABC-0007"
}

@test "wt-rm passes through text input unchanged" {
    # Given: repository with worktree.wt.prefix configured
    # And: worktree created with git wt feature-login
    # When: user runs git wt-rm feature-login
    # Then: worktree should be removed

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    git_test config worktree.wt.prefix "TICKET-"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create with text input
    run git_test wt feature-login 2>&1
    git_test show-ref --verify --quiet "refs/heads/feature-login"

    # Remove with same text input
    run git_test wt-rm feature-login <<< "y" 2>&1

    # Verify worktree was successfully removed
    assert_success
    assert_output --partial "Removed worktree"
    assert_output --partial "feature-login"
}

@test "wt-rm handles already-prefixed input" {
    # Given: repository with worktree.wt.prefix configured to "OTHER-"
    # And: worktree created with git wt EXISTING-123
    # When: user runs git wt-rm EXISTING-123
    # Then: worktree should be removed

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    git_test config worktree.wt.prefix "OTHER-"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create with already-prefixed input
    run git_test wt EXISTING-123 2>&1
    git_test show-ref --verify --quiet "refs/heads/EXISTING-123"

    # Remove with same already-prefixed input
    run git_test wt-rm EXISTING-123 <<< "y" 2>&1

    # Verify worktree was successfully removed
    assert_success
    assert_output --partial "Removed worktree"
    assert_output --partial "EXISTING-123"
}

@test "wt-rm applies same input detection as wt for mixed alphanumeric" {
    # Given: repository with worktree.wt.prefix configured
    # And: worktree created with git wt ABC-123
    # When: user runs git wt-rm ABC-123
    # Then: worktree should be removed

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    git_test config worktree.wt.prefix "OTHER-"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create with already-prefixed input
    run git_test wt ABC-123 2>&1
    git_test show-ref --verify --quiet "refs/heads/ABC-123"

    # Remove with same input
    run git_test wt-rm ABC-123 <<< "y" 2>&1

    # Verify worktree was successfully removed
    assert_success
    assert_output --partial "Removed worktree"
    assert_output --partial "ABC-123"
}