#!/usr/bin/env bats
#
# Tests for: WTA - Error Handling
# Feature: Error detection and user-friendly messages
# Requirements: Derived from git_config_alias_worktree.sh
# Generated by: /mdt:tests
# Status: GREEN (tests actual error scenarios)
#

setup() {
    load 'test_helper/common-setup.bash'
    _common_setup
}

teardown() {
    if [[ -n "$TEST_REPO_DIR" && -d "$TEST_REPO_DIR" ]]; then
        cleanup_test_repo "$TEST_REPO_DIR"
    fi
    _common_teardown
}

# Feature: Duplicate Worktree Detection

@test "error: worktree directory already exists" {
    # Given: a worktree directory already exists
    # When: attempting to create another with same name
    # Then: should exit with error code 1 and helpful message

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create existing worktree directory manually
    mkdir -p "$TEST_REPO_DIR/.gitWT/WTA-123"

    # Try to create worktree - should fail
    run git_test wt 123 2>&1 || true

    assert_failure
    assert_output --partial "Worktree already exists"
    assert_output --partial "$TEST_REPO_DIR/.gitWT/WTA-123"

    # Cleanup: manually remove the directory
    rmdir "$TEST_REPO_DIR/.gitWT/WTA-123" 2>/dev/null || true
}

@test "error: branch exists without worktree" {
    # Given: a branch exists but has no worktree
    # When: attempting to create worktree with same branch name
    # Then: should exit with error code 2 and instructions

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create a branch without worktree
    git_test checkout -q -b WTA-123
    git_test checkout -q -

    # Try to create worktree with same branch name
    run git_test wt 123 2>&1 || true

    assert_failure
    assert_output --partial "Branch \"WTA-123\" already exists but has no worktree"
    assert_output --partial "git worktree add"

    # Cleanup: remove the branch
    git_test branch -D WTA-123 2>/dev/null || true
}

@test "provides: helpful message for existing branch error" {
    # Given: branch exists without worktree
    # When: error occurs
    # Then: message should include git command to fix

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    git_test checkout -q -b WTA-124
    git_test checkout -q -

    # Try to create worktree with same branch name
    run git_test wt 124 2>&1 || true

    assert_output --partial "already exists but has no worktree"
    assert_output --partial "git worktree add"

    # Cleanup: remove the branch
    git_test branch -D WTA-124 2>/dev/null || true
}

@test "error: missing worktree.wt.defaultPath config" {
    # Given: no worktree.wt.defaultPath configured
    # When: running git wt
    # Then: should show warning and offer to set default

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    create_mdt_config "$TEST_REPO_DIR" "WTA"

    # Clear any existing config
    git_test config --unset worktree.wt.defaultPath 2>/dev/null || true
    git_test config --unset worktree.defaultPath 2>/dev/null || true
    git_test config --global --unset worktree.wt.defaultPath 2>/dev/null || true
    git_test config --global --unset worktree.defaultPath 2>/dev/null || true

    # Run with WT_TEST_RESPONSE="n" to decline the prompt
    WT_TEST_RESPONSE="n" run git_test wt 555 2>&1 || true

    # Should show warning about missing config
    assert_output --partial "worktree.wt.defaultPath is not configured"
    assert_output --partial "git config --global"
    assert_output --partial "git config worktree.wt.defaultPath"
}

@test "suggests: configuration examples on missing config" {
    # Given: no worktree.wt.defaultPath configured
    # When: showing help message
    # Then: should display multiple configuration examples

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    create_mdt_config "$TEST_REPO_DIR" "WTA"

    # Clear any existing config
    git_test config --unset worktree.wt.defaultPath 2>/dev/null || true
    git_test config --unset worktree.defaultPath 2>/dev/null || true
    git_test config --global --unset worktree.wt.defaultPath 2>/dev/null || true
    git_test config --global --unset worktree.defaultPath 2>/dev/null || true

    # Run with WT_TEST_RESPONSE="n" to decline the prompt
    WT_TEST_RESPONSE="n" run git_test wt 666 2>&1 || true

    # Should show placeholder examples
    assert_output --partial "{worktree_name}"
    assert_output --partial "{project_dir}"

    # Should show config examples
    assert_output --partial ".gitWT/{worktree_name}"
    assert_output --partial "~/worktrees/{worktree_name}"

    # Should show command examples
    assert_output --partial "git config --global"
    assert_output --partial "git config worktree.wt.defaultPath"
}

