#!/usr/bin/env bats
#
# Tests for: WTA - Error Handling
# Feature: Error detection and user-friendly messages
# Requirements: Derived from git_config_alias_worktree.sh
# Generated by: /mdt:tests
# Status: RED (implementation pending)
#

setup() {
    load 'test_helper/common-setup.bash'
    _common_setup
}

teardown() {
    if [[ -n "$TEST_REPO_DIR" && -d "$TEST_REPO_DIR" ]]; then
        cleanup_test_repo "$TEST_REPO_DIR"
    fi
    _common_teardown
}

# Feature: Duplicate Worktree Detection

@test "error: worktree directory already exists" {
    # Given: a worktree directory already exists
    # When: attempting to create another with same name
    # Then: should exit with error code 1 and helpful message

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    # Create existing worktree directory
    mkdir -p "$TEST_REPO_DIR/.gitWT/WTA-123"

    # Simulate the check
    worktree_path="$TEST_REPO_DIR/.gitWT/WTA-123"

    if [ -d "$worktree_path" ]; then
        error_message="error: Worktree already exists at $worktree_path"
        exit_code=1
    fi

    assert_equal "$exit_code" 1
    assert_regex "$error_message" "error: Worktree already exists"
}

@test "error: branch exists without worktree" {
    # Given: a branch exists but has no worktree
    # When: attempting to create worktree with same branch name
    # Then: should exit with error code 2 and instructions

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    # Create a branch without worktree
    git_test checkout -q -b WTA-123
    git_test checkout -q -

    # Simulate the check
    worktree="WTA-123"

    if git_test show-ref --verify --quiet "refs/heads/$worktree"; then
        error_code=2
        has_branch_without_worktree=true
    fi

    assert_equal "$error_code" 2
    assert "$has_branch_without_worktree"
}

@test "provides: helpful message for existing branch error" {
    # Given: branch exists without worktree
    # When: error occurs
    # Then: message should include git command to fix

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    git_test checkout -q -b WTA-124
    git_test checkout -q -

    worktree="WTA-124"
    worktree_path="$TEST_REPO_DIR/.gitWT/WTA-124"
    relative_flag="--relative-paths"

    if git_test show-ref --verify --quiet "refs/heads/$worktree"; then
        error_message="error: Branch \"$worktree\" already exists but has no worktree"
        suggestion="To create worktree for existing branch: git worktree add $relative_flag \"$worktree_path\" \"$worktree\""
    fi

    assert_regex "$error_message" "already exists but has no worktree"
    assert_regex "$suggestion" "git worktree add"
}

@test "error: missing worktree.defaultPath config" {
    # Given: no worktree.defaultPath configured
    # When: running git wt
    # Then: should show warning and offer to set default

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    # Clear any existing config
    git_test config --unset worktree.defaultPath 2>/dev/null || true
    git_test config --global --unset worktree.defaultPath 2>/dev/null || true

    # Check config
    default_path=$(git_test config worktree.defaultPath 2>/dev/null || git_test config --global worktree.defaultPath 2>/dev/null || echo "")

    if [ -z "$default_path" ]; then
        has_missing_config=true
        shows_warning=true
    fi

    # The variables are set as strings, convert to proper boolean checks
    [ "$has_missing_config" = true ]  # This should be true
    [ "$shows_warning" = true ]       # This should be true
}

@test "suggests: configuration examples on missing config" {
    # Given: no worktree.defaultPath configured
    # When: showing help message
    # Then: should display multiple configuration examples

    # Simulate the help message content
    help_message="warning: worktree.defaultPath is not configured

This setting defines where worktrees are created. Use placeholders: {worktree_name}, {project_dir}
If {worktree_name} is not in the path, it will be appended.
Examples:
  - Relative: .gitWT/{worktree_name}  (creates worktrees inside repo)
  - Relative: .gitWT  (worktree_name will be appended: .gitWT/MDT-122)
  - Absolute: ~/worktrees/{worktree_name}  (creates worktrees outside repo)
  - With project: /worktrees/{project_dir}-{worktree_name}
  - Relative: ../{project_dir}_{worktree_name}

Placeholders:
  - {worktree_name}: The branch/worktree name (e.g., MDT-123)
  - {project_dir}: Basename of git repository (e.g., super-mario)

To set globally: git config --global worktree.defaultPath \".gitWT/{worktree_name}\"
To set locally:  git config worktree.defaultPath \"~/worktrees/{worktree_name}\""

    assert_regex "$help_message" "{worktree_name}"
    assert_regex "$help_message" "{project_dir}"
    assert_regex "$help_message" "git config --global"
    assert_regex "$help_message" "git config worktree.defaultPath"
}
