#!/usr/bin/env bats
#
# Tests for: WTA-002 - Generic Ticket Prefix Configuration
# Feature: Generic ticket prefix configuration via git config
# Requirements: R1.1-R1.4, R4.2 from WTA-002/requirements.md
# Generated by: /mdt:tests
# Status: RED (implementation pending)
#

setup() {
    load 'test_helper/common-setup.bash'
    _common_setup
}

teardown() {
    if [[ -n "$TEST_REPO_DIR" && -d "$TEST_REPO_DIR" ]]; then
        cleanup_test_repo "$TEST_REPO_DIR"
    fi
    _common_teardown
}

# Feature: Generic Ticket Prefix Configuration

@test "creates worktree with generic prefix from git config" {
    # Given: repository with worktree.wt.prefix configured to "ABC-"
    # When: user runs git wt 101
    # Then: branch named ABC-101 should exist

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    git_test config worktree.wt.prefix "ABC-"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    run git_test wt 101 2>&1

    # Verify branch was created with configured prefix
    git_test show-ref --verify --quiet "refs/heads/ABC-101"

    # Cleanup
    git_test worktree remove ".gitWT/ABC-101" 2>/dev/null || true
}

@test "creates worktree with hash prefix from git config" {
    # Given: repository with worktree.wt.prefix configured to "#"
    # When: user runs git wt 42
    # Then: branch named #42 should exist

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    git_test config worktree.wt.prefix "#"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    run git_test wt 42 2>&1

    git_test show-ref --verify --quiet "refs/heads/#42"

    # Cleanup
    git_test worktree remove ".gitWT/#42" 2>/dev/null || true
}

@test "creates worktree without prefix for text input" {
    # Given: repository with worktree.wt.prefix configured
    # When: user runs git wt feature-login (text input)
    # Then: branch named feature-login should exist (prefix NOT applied)

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    git_test config worktree.wt.prefix "ABC-"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    run git_test wt feature-login 2>&1

    # Verify branch was created without prefix (text input)
    git_test show-ref --verify --quiet "refs/heads/feature-login"

    # Cleanup
    git_test worktree remove ".gitWT/feature-login" 2>/dev/null || true
}

@test "creates worktree without prefix when not configured" {
    # Given: repository without worktree.wt.prefix configured
    # When: user runs git wt 101
    # Then: branch named 101 should exist (no prefix)

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    run git_test wt 101 2>&1

    git_test show-ref --verify --quiet "refs/heads/101"

    # Cleanup
    git_test worktree remove ".gitWT/101" 2>/dev/null || true
}

@test "git config prefix overrides MDT auto-detected prefix" {
    # Given: repository with .mdt-config.toml (code = "TEST")
    # And: worktree.wt.prefix is set to "OVERRIDE-"
    # When: user runs git wt 123
    # Then: branch named OVERRIDE-123 should exist (git config wins)

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    create_mdt_config "$TEST_REPO_DIR" "TEST"
    git_test config worktree.wt.prefix "OVERRIDE-"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    run git_test wt 123 2>&1

    # Git config should override MDT auto-detection
    git_test show-ref --verify --quiet "refs/heads/OVERRIDE-123"

    # Cleanup
    git_test worktree remove ".gitWT/OVERRIDE-123" 2>/dev/null || true
}
