#!/usr/bin/env bats
#
# Tests for: WTA-002 - Input Type Detection and Handling
# Feature: Intelligent handling of different input formats
# Requirements: R3.1-R3.4 from WTA-002/requirements.md
# Generated by: /mdt:tests
# Status: RED (implementation pending)
#

setup() {
    load 'test_helper/common-setup.bash'
    _common_setup
}

teardown() {
    if [[ -n "$TEST_REPO_DIR" && -d "$TEST_REPO_DIR" ]]; then
        cleanup_test_repo "$TEST_REPO_DIR"
    fi
    _common_teardown
}

# Feature: Input Type Detection and Handling

@test "passes through already-prefixed input unchanged" {
    # Given: repository with worktree.wt.prefix configured to "ABC-"
    # When: user runs git wt PROJ-123 (already prefixed)
    # Then: branch named PROJ-123 should exist (not ABC-PROJ-123)

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    git_test config worktree.wt.prefix "ABC-"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    run git_test wt PROJ-123 2>&1

    git_test show-ref --verify --quiet "refs/heads/PROJ-123"

    # Cleanup
    git_test worktree remove ".gitWT/PROJ-123" 2>/dev/null || true
}

@test "applies prefix to pure numeric input" {
    # Given: repository with worktree.wt.prefix configured
    # And: worktree.wt.zeroPadDigits configured
    # When: user runs git wt 101 (pure numeric)
    # Then: branch with prefix and padding should exist

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    git_test config worktree.wt.prefix "JIRA-"
    git_test config worktree.wt.zeroPadDigits 4
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    run git_test wt 101 2>&1

    git_test show-ref --verify --quiet "refs/heads/JIRA-0101"

    # Cleanup
    git_test worktree remove ".gitWT/JIRA-0101" 2>/dev/null || true
}

@test "passes through text input unchanged" {
    # Given: repository with worktree.wt.prefix configured
    # When: user runs git wt feature-auth (contains letters)
    # Then: branch named feature-auth should exist (no prefix)

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    git_test config worktree.wt.prefix "TICKET-"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    run git_test wt feature-auth 2>&1

    git_test show-ref --verify --quiet "refs/heads/feature-auth"

    # Cleanup
    git_test worktree remove ".gitWT/feature-auth" 2>/dev/null || true
}

@test "wt-rm locates worktree created with prefix" {
    # Given: repository with worktree.wt.prefix configured to "PROJ-"
    # And: worktree created with git wt 101 (branch PROJ-101)
    # When: user runs git wt-rm 101
    # Then: PROJ-101 worktree should be removed

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    git_test config worktree.wt.prefix "PROJ-"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create worktree
    run git_test wt 101 2>&1
    git_test show-ref --verify --quiet "refs/heads/PROJ-101"

    # Remove with short input
    run git_test wt-rm 101 <<< "y" 2>&1

    # Verify worktree was successfully removed
    assert_success
    assert_output --partial "Removed worktree"
    assert_output --partial "PROJ-101"
}

@test "wt-rm accepts full worktree name" {
    # Given: repository with worktree.wt.prefix configured to "PROJ-"
    # And: worktree created with git wt 101 (branch PROJ-101)
    # When: user runs git wt-rm PROJ-101
    # Then: worktree should be removed

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    git_test config worktree.wt.prefix "PROJ-"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create worktree
    run git_test wt 101 2>&1
    git_test show-ref --verify --quiet "refs/heads/PROJ-101"

    # Remove with full name
    run git_test wt-rm PROJ-101 <<< "y" 2>&1

    # Verify worktree was successfully removed
    assert_success
    assert_output --partial "Removed worktree"
    assert_output --partial "PROJ-101"
}

@test "handles mixed alphanumeric input as already prefixed" {
    # Given: repository with worktree.wt.prefix configured
    # When: user runs git wt ABC-123
    # Then: branch named ABC-123 should exist

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    git_test config worktree.wt.prefix "OTHER-"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    run git_test wt ABC-123 2>&1

    git_test show-ref --verify --quiet "refs/heads/ABC-123"

    # Cleanup
    git_test worktree remove ".gitWT/ABC-123" 2>/dev/null || true
}

@test "handles feature branch with numbers as text input" {
    # Given: repository with worktree.wt.prefix configured
    # When: user runs git wt feature-123
    # Then: branch named feature-123 should exist (no prefix)

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    git_test config worktree.wt.prefix "TICKET-"
    git_test config worktree.wt.zeroPadDigits 3
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    run git_test wt feature-123 2>&1

    git_test show-ref --verify --quiet "refs/heads/feature-123"

    # Cleanup
    git_test worktree remove ".gitWT/feature-123" 2>/dev/null || true
}
