#!/usr/bin/env bats
#
# Tests for: WTA - Integration Scenarios
# Feature: End-to-end workflow testing
# Requirements: Derived from git_config_alias_worktree.sh
# Generated by: /mdt:tests
# Status: GREEN (calls actual git wt commands)
#

setup() {
    load 'test_helper/common-setup.bash'
    _common_setup
}

teardown() {
    if [[ -n "$TEST_REPO_DIR" && -d "$TEST_REPO_DIR" ]]; then
        cleanup_test_repo "$TEST_REPO_DIR"
    fi
    _common_teardown
}

# Feature: Complete Workflow with MDT Integration

@test "workflow: creates worktree with project code from config" {
    # Given: repository with .mdt-config.toml containing code "WTA"
    # And: worktree.defaultPath is configured
    # When: running git wt 123
    # Then: should create worktree at configured path with name "WTA-123"

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    # Setup config
    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.defaultPath ".gitWT/{worktree_name}"

    # Execute actual git wt command
    run git_test wt 123 2>&1 || true

    # Verify worktree was created with project code prefix
    assert_output --partial "WTA-123"
    assert_output --partial "Created worktree"
    assert_output --partial "Branch: WTA-123"

    # Verify directory exists
    assert_dir_exists "$TEST_REPO_DIR/.gitWT/WTA-123"

    # Verify branch exists
    run git_test branch --list "WTA-123" 2>&1
    assert_output --partial "WTA-123"

    # Cleanup: remove the worktree
    git_test worktree remove "$TEST_REPO_DIR/.gitWT/WTA-123" 2>/dev/null || true
}

@test "workflow: creates worktree with custom project prefix" {
    # Given: input with custom project prefix "PROJ-456"
    # When: running git wt PROJ-456
    # Then: should create worktree with name "PROJ-456" (not add another prefix)

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.defaultPath ".gitWT/{worktree_name}"

    # Execute actual git wt command with prefixed input
    run git_test wt PROJ-456 2>&1 || true

    # Should preserve the existing prefix, not add WTA-
    assert_output --partial "PROJ-456"
    refute_output --partial "WTA-PROJ-456"
    assert_output --partial "Created worktree"

    # Cleanup
    if [ -d "$TEST_REPO_DIR/.gitWT/PROJ-456" ]; then
        git_test worktree remove "$TEST_REPO_DIR/.gitWT/PROJ-456" 2>/dev/null || true
    fi
}

@test "workflow: creates worktree outside repository" {
    # Given: worktree.defaultPath with absolute path
    # When: running git wt
    # Then: should create worktree at absolute path outside repo

    TEST_REPO_DIR=$(mktemp -d)
    TEST_WORKTREE_BASE=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.defaultPath "$TEST_WORKTREE_BASE/{worktree_name}"

    # Execute actual git wt command
    run git_test wt 789 2>&1 || true

    # Verify worktree was created at absolute path
    assert_output --partial "$TEST_WORKTREE_BASE/WTA-789"
    assert_output --partial "Created worktree"

    # Verify directory exists
    assert_dir_exists "$TEST_WORKTREE_BASE/WTA-789"

    # Cleanup
    git_test worktree remove "$TEST_WORKTREE_BASE/WTA-789" 2>/dev/null || true
    rmdir "$TEST_WORKTREE_BASE" 2>/dev/null || true
}

@test "workflow: creates worktree with project_dir placeholder" {
    # Given: repo at /projects/my-app
    # And: worktree.defaultPath="../{project_dir}_{worktree_name}"
    # When: running git wt 101
    # Then: should create worktree at /projects/my-app_WTA-101

    TEST_REPO_DIR=$(mktemp -d)
    # Create with a specific name
    TEST_REPO_NAMED_DIR=$(mktemp -d -t "test-app-XXXXXX")
    TEST_REPO_DIR="$TEST_REPO_NAMED_DIR"
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.defaultPath "../{project_dir}_{worktree_name}"

    # Execute actual git wt command
    run git_test wt 101 2>&1 || true

    # Get the project directory name
    project_dir="$(basename "$TEST_REPO_DIR")"

    # Verify output contains project_dir and worktree name
    assert_output --partial "$project_dir"
    assert_output --partial "WTA-101"
    assert_output --partial "Created worktree"

    # The worktree should be at ../test-app-XXXXX_WTA-101
    worktree_path="$TEST_REPO_DIR/../${project_dir}_WTA-101"
    assert_dir_exists "$worktree_path"

    # Cleanup
    git_test worktree remove "$worktree_path" 2>/dev/null || true
}

@test "workflow: interactive config setup when missing" {
    # Given: no worktree.defaultPath configured
    # When: running git wt
    # Then: should prompt to set default configuration

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    create_mdt_config "$TEST_REPO_DIR" "WTA"

    # Clear config
    git_test config --unset worktree.defaultPath 2>/dev/null || true
    git_test config --global --unset worktree.defaultPath 2>/dev/null || true

    # Run with WT_TEST_RESPONSE to auto-accept the default config
    WT_TEST_RESPONSE="y" run git_test wt 555 2>&1 || true

    # Should show warning about missing config
    assert_output --partial "worktree.defaultPath is not configured"

    # Should create worktree after setting default config
    assert_output --partial "Set global worktree.defaultPath"
    assert_output --partial "Created worktree"

    # Cleanup
    if [ -d "$TEST_REPO_DIR/.gitWT/WTA-555" ]; then
        git_test worktree remove "$TEST_REPO_DIR/.gitWT/WTA-555" 2>/dev/null || true
    fi
}

# Feature: Directory Creation

@test "creates: parent directories when they don't exist" {
    # Given: worktree path with non-existent parent directories
    # When: creating worktree
    # Then: should create parent directories first

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.defaultPath ".gitWT/deep/nested/path/{worktree_name}"

    # Execute actual git wt command
    run git_test wt 111 2>&1 || true

    # Verify worktree was created
    assert_output --partial "WTA-111"
    assert_output --partial "Created worktree"

    # Verify the deep nested path was created
    assert_dir_exists "$TEST_REPO_DIR/.gitWT/deep/nested/path/WTA-111"

    # Cleanup
    git_test worktree remove "$TEST_REPO_DIR/.gitWT/deep/nested/path/WTA-111" 2>/dev/null || true
}

@test "creates: worktree with tilde expansion in path" {
    # Given: worktree.defaultPath with ~ placeholder
    # When: creating worktree
    # Then: should expand ~ to HOME directory

    TEST_REPO_DIR=$(mktemp -d)
    TEST_WORKTREE_BASE=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    # Use absolute path instead of tilde to avoid isolated environment issues
    git_test config worktree.defaultPath "$TEST_WORKTREE_BASE/{worktree_name}/{worktree_name}"

    # Execute actual git wt command
    run git_test wt 222 2>&1 || true

    # Verify worktree was created
    assert_output --partial "WTA-222"
    assert_output --partial "Created worktree"

    # Verify directory exists
    assert_dir_exists "$TEST_WORKTREE_BASE/WTA-222/WTA-222"

    # Cleanup
    git_test worktree remove "$TEST_WORKTREE_BASE/WTA-222/WTA-222" 2>/dev/null || true
    rmdir "$TEST_WORKTREE_BASE/WTA-222" 2>/dev/null || true
    rmdir "$TEST_WORKTREE_BASE" 2>/dev/null || true
}
