#!/usr/bin/env bats
#
# Tests for: WTA - Project Code Resolution
# Feature: Automatic project code detection from .mdt-config.toml
# Requirements: Derived from git_config_alias_worktree.sh
# Generated by: /mdt:tests
# Status: GREEN (calls actual git wt alias)
#

setup() {
    load 'test_helper/common-setup.bash'
    _common_setup
}

teardown() {
    if [[ -n "$TEST_REPO_DIR" && -d "$TEST_REPO_DIR" ]]; then
        cleanup_test_repo "$TEST_REPO_DIR"
    fi
    _common_teardown
}

# Feature: Project Code Resolution from .mdt-config.toml

@test "reads: project code from .mdt-config.toml" {
    # Given: a repository with .mdt-config.toml
    # When: input is plain 3-digit number
    # Then: worktree name should be prefixed with project code

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    # Create .mdt-config.toml with project code
    create_mdt_config "$TEST_REPO_DIR" "TEST"

    # Verify config file exists
    assert_file_exist "$TEST_REPO_DIR/.mdt-config.toml"

    # Set default path to avoid interactive prompts
    git_test config worktree.defaultPath ".gitWT/{worktree_name}"

    # Call actual git wt command
    run git_test wt 123 2>&1 || true

    # Verify worktree was created with project code prefix
    assert_output --partial "TEST-123"
    assert_output --partial "Created worktree"

    # Cleanup: remove the worktree
    if [ -d "$TEST_REPO_DIR/.gitWT/TEST-123" ]; then
        git_test worktree remove "$TEST_REPO_DIR/.gitWT/TEST-123" 2>/dev/null || true
    fi
}

@test "fallback: uses plain number when config file missing" {
    # Given: a repository without .mdt-config.toml
    # When: input is plain 3-digit number
    # Then: worktree name should be plain ticket number

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    # Don't create .mdt-config.toml - test fallback behavior

    # Set default path to avoid interactive prompts
    git_test config worktree.defaultPath ".gitWT/{worktree_name}"

    # Call actual git wt command
    run git_test wt 123 2>&1 || true

    # Verify worktree was created without project code (just ticket number)
    assert_output --partial "123"
    refute_output --partial "TEST-123"
    refute_output --partial "WTA-123"
    assert_output --partial "Created worktree"

    # Cleanup: remove the worktree
    if [ -d "$TEST_REPO_DIR/.gitWT/123" ]; then
        git_test worktree remove "$TEST_REPO_DIR/.gitWT/123" 2>/dev/null || true
    fi
}

@test "preserves: existing prefix when already provided" {
    # Given: input with project prefix (e.g., "MDT-123")
    # When: worktree name is constructed
    # Then: should not add another prefix

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    create_mdt_config "$TEST_REPO_DIR" "TEST"

    # Set default path to avoid interactive prompts
    git_test config worktree.defaultPath ".gitWT/{worktree_name}"

    # Input already has prefix - call actual git wt command
    run git_test wt MDT-456 2>&1 || true

    # Should preserve the existing prefix, not add TEST-
    assert_output --partial "MDT-456"
    refute_output --partial "TEST-MDT-456"
    assert_output --partial "Created worktree"

    # Cleanup: remove the worktree
    if [ -d "$TEST_REPO_DIR/.gitWT/MDT-456" ]; then
        git_test worktree remove "$TEST_REPO_DIR/.gitWT/MDT-456" 2>/dev/null || true
    fi
}

@test "handles: empty project code in config" {
    # Given: .mdt-config.toml with empty code field
    # When: input is plain 3-digit number
    # Then: should fall back to plain ticket number

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    # Create config with empty code
    cat >"$TEST_REPO_DIR/.mdt-config.toml" <<EOF
[project]
code = ""
EOF

    # Set default path to avoid interactive prompts
    git_test config worktree.defaultPath ".gitWT/{worktree_name}"

    # Call actual git wt command
    run git_test wt 789 2>&1 || true

    # Verify worktree was created without project code (just ticket number)
    assert_output --partial "789"
    refute_output --partial "WTA-789"
    assert_output --partial "Created worktree"

    # Cleanup: remove the worktree
    if [ -d "$TEST_REPO_DIR/.gitWT/789" ]; then
        git_test worktree remove "$TEST_REPO_DIR/.gitWT/789" 2>/dev/null || true
    fi
}

@test "extracts: correct code format from config" {
    # Given: .mdt-config.toml with double-quoted code value
    # When: parsing the code field
    # Then: should extract the code without quotes

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    # Test with double quotes (standard TOML)
    cat >"$TEST_REPO_DIR/.mdt-config.toml" <<EOF
[project]
code = "FOO"
EOF

    # Set default path to avoid interactive prompts
    git_test config worktree.defaultPath ".gitWT/{worktree_name}"

    # Call actual git wt command
    run git_test wt 999 2>&1 || true

    # Verify worktree was created with correct project code
    assert_output --partial "FOO-999"
    assert_output --partial "Created worktree"

    # Cleanup: remove the worktree
    if [ -d "$TEST_REPO_DIR/.gitWT/FOO-999" ]; then
        git_test worktree remove "$TEST_REPO_DIR/.gitWT/FOO-999" 2>/dev/null || true
    fi

    # Note: Single quotes (TOML literal strings) are not supported due to
    # git alias quoting limitations. Use double quotes for the code field.
}
