#!/usr/bin/env bats
#
# Tests for: WTA - Path Resolution
# Feature: worktree.defaultPath configuration and placeholder substitution
# Requirements: Derived from git_config_alias_worktree.sh
# Generated by: /mdt:tests
# Status: RED (implementation pending)
#

setup() {
    load 'test_helper/common-setup.bash'
    _common_setup
}

teardown() {
    if [[ -n "$TEST_REPO_DIR" && -d "$TEST_REPO_DIR" ]]; then
        cleanup_test_repo "$TEST_REPO_DIR"
    fi
    _common_teardown
}

# Feature: Path Placeholder Substitution

@test "substitutes: {worktree_name} placeholder in path" {
    # Given: worktree.defaultPath with {worktree_name} placeholder
    # When: constructing worktree path
    # Then: placeholder should be replaced with worktree name

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    default_path=".gitWT/{worktree_name}"
    worktree="WTA-123"
    project_dir="$(basename "$(git_test rev-parse --show-toplevel)")"

    # Replace {project_dir} placeholder first
    if [[ "$default_path" == *"{project_dir}"* ]]; then
        default_path_with_project=$(echo "$default_path" | sed "s/{project_dir}/$project_dir/g")
    else
        default_path_with_project="$default_path"
    fi

    # Then replace {worktree_name}
    if [[ "$default_path_with_project" == *"{worktree_name}"* ]]; then
        worktree_path=$(echo "$default_path_with_project" | sed "s/{worktree_name}/$worktree/g")
    else
        default_path_with_project="${default_path_with_project%/}"
        worktree_path="$default_path_with_project/$worktree"
    fi

    assert_equal "$worktree_path" ".gitWT/WTA-123"
}

@test "substitutes: {project_dir} placeholder in path" {
    # Given: worktree.defaultPath with {project_dir} placeholder
    # When: constructing worktree path
    # Then: placeholder should be replaced with repo basename

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    # The temp dir basename is our "project_dir"
    expected_project_dir="$(basename "$TEST_REPO_DIR")"

    default_path="../{project_dir}_{worktree_name}"
    worktree="WTA-123"

    # Replace {project_dir} placeholder first
    if [[ "$default_path" == *"{project_dir}"* ]]; then
        default_path_with_project=$(echo "$default_path" | sed "s/{project_dir}/$expected_project_dir/g")
    else
        default_path_with_project="$default_path"
    fi

    # Then replace {worktree_name}
    if [[ "$default_path_with_project" == *"{worktree_name}"* ]]; then
        worktree_path=$(echo "$default_path_with_project" | sed "s/{worktree_name}/$worktree/g")
    else
        default_path_with_project="${default_path_with_project%/}"
        worktree_path="$default_path_with_project/$worktree"
    fi

    assert_equal "$worktree_path" "../${expected_project_dir}_WTA-123"
}

@test "appends: worktree name when placeholder not present" {
    # Given: worktree.defaultPath without {worktree_name} placeholder
    # When: constructing worktree path
    # Then: worktree name should be appended with separator

    default_path=".gitWT"
    worktree="WTA-123"
    project_dir="test-project"

    # No {worktree_name} placeholder
    default_path_with_project="$default_path"

    if [[ "$default_path_with_project" == *"{worktree_name}"* ]]; then
        worktree_path=$(echo "$default_path_with_project" | sed "s/{worktree_name}/$worktree/g")
    else
        default_path_with_project="${default_path_with_project%/}"
        worktree_path="$default_path_with_project/$worktree"
    fi

    assert_equal "$worktree_path" ".gitWT/WTA-123"
}

@test "expands: tilde (~) to HOME directory" {
    # Given: worktree.defaultPath starting with ~
    # When: constructing worktree path
    # Then: ~ should be expanded to $HOME

    default_path="~/worktrees/{worktree_name}"
    worktree="WTA-123"

    default_path_with_project="$default_path"
    worktree_path=$(echo "$default_path_with_project" | sed "s/{worktree_name}/$worktree/g")
    worktree_path="${worktree_path/#\~/$HOME}"

    # Path should start with HOME, not ~
    assert_regex "$worktree_path" "^$HOME"
    refute_regex "$worktree_path" "^~/"
}

@test "handles: absolute paths correctly" {
    # Given: worktree.defaultPath as absolute path
    # When: constructing worktree path
    # Then: should not prepend repo root

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    default_path="/worktrees/{worktree_name}"
    worktree="WTA-123"

    default_path_with_project="$default_path"
    worktree_path=$(echo "$default_path_with_project" | sed "s/{worktree_name}/$worktree/g")
    worktree_path="${worktree_path/#\~/$HOME}"

    if [[ "$worktree_path" == /* ]]; then
        relative_flag="--no-relative-paths"
    else
        repo_root="$(git_test rev-parse --show-toplevel)"
        worktree_path="$repo_root/$worktree_path"
        relative_flag="--relative-paths"
    fi

    assert_equal "$relative_flag" "--no-relative-paths"
    assert_equal "$worktree_path" "/worktrees/WTA-123"
}

@test "handles: relative paths with repo root" {
    # Given: worktree.defaultPath as relative path
    # When: constructing worktree path
    # Then: should prepend repo root

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    default_path=".gitWT/{worktree_name}"
    worktree="WTA-123"
    repo_root="$(git_test rev-parse --show-toplevel)"

    default_path_with_project="$default_path"
    worktree_path=$(echo "$default_path_with_project" | sed "s/{worktree_name}/$worktree/g")

    if [[ "$worktree_path" == /* ]]; then
        relative_flag="--no-relative-paths"
    else
        worktree_path="$repo_root/$worktree_path"
        relative_flag="--relative-paths"
    fi

    assert_equal "$relative_flag" "--relative-paths"
    assert_equal "$worktree_path" "$repo_root/.gitWT/WTA-123"
}

@test "combines: multiple placeholders correctly" {
    # Given: worktree.defaultPath with both placeholders
    # When: constructing worktree path
    # Then: both should be replaced in correct order

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    expected_project_dir="$(basename "$TEST_REPO_DIR")"
    default_path="~/worktrees/{project_dir}/{worktree_name}"
    worktree="WTA-123"

    # Replace {project_dir} first, then {worktree_name}
    if [[ "$default_path" == *"{project_dir}"* ]]; then
        default_path_with_project=$(echo "$default_path" | sed "s/{project_dir}/$expected_project_dir/g")
    else
        default_path_with_project="$default_path"
    fi

    if [[ "$default_path_with_project" == *"{worktree_name}"* ]]; then
        worktree_path=$(echo "$default_path_with_project" | sed "s/{worktree_name}/$worktree/g")
    else
        default_path_with_project="${default_path_with_project%/}"
        worktree_path="$default_path_with_project/$worktree"
    fi

    worktree_path="${worktree_path/#\~/$HOME}"

    assert_regex "$worktree_path" "^$HOME/worktrees/$expected_project_dir/WTA-123$"
}
