#!/usr/bin/env bats
#
# Tests for: WTA - Project Code Resolution
# Feature: Automatic project code detection from .mdt-config.toml
# Requirements: Derived from git_config_alias_worktree.sh
# Generated by: /mdt:tests
# Status: RED (implementation pending)
#

setup() {
    load 'test_helper/common-setup.bash'
    _common_setup
}

teardown() {
    if [[ -n "$TEST_REPO_DIR" && -d "$TEST_REPO_DIR" ]]; then
        cleanup_test_repo "$TEST_REPO_DIR"
    fi
    _common_teardown
}

# Feature: Project Code Resolution from .mdt-config.toml

@test "reads: project code from .mdt-config.toml" {
    # Given: a repository with .mdt-config.toml
    # When: input is plain 3-digit number
    # Then: worktree name should be prefixed with project code

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    # Create .mdt-config.toml with project code
    create_mdt_config "$TEST_REPO_DIR" "TEST"

    # Verify config file exists
    assert_file_exist "$TEST_REPO_DIR/.mdt-config.toml"

    # Set default path to avoid interactive prompts
    git_test config worktree.defaultPath ".gitWT/{worktree_name}"

    # Simulate the code extraction logic
    worktree="123"
    ticket_number=$(echo "$worktree" | grep -Eo "[0-9][0-9][0-9]")
    dot_config="$(git_test rev-parse --show-toplevel)/.mdt-config.toml"

    if [ -f "$dot_config" ]; then
        project_code=$(grep "^code = " "$dot_config" | cut -d"=" -f2 | tr -d " \"")
        if [ -n "$project_code" ]; then
            worktree="${project_code}-${ticket_number}"
        fi
    fi

    assert_equal "$worktree" "TEST-123"
}

@test "fallback: uses plain number when config file missing" {
    # Given: a repository without .mdt-config.toml
    # When: input is plain 3-digit number
    # Then: worktree name should be plain ticket number

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    # Don't create .mdt-config.toml
    worktree="123"
    ticket_number=$(echo "$worktree" | grep -Eo "[0-9][0-9][0-9]")
    dot_config="$(git_test rev-parse --show-toplevel)/.mdt-config.toml"

    if [[ "$worktree" =~ ^[0-9][0-9][0-9]$ ]]; then
        if [ -f "$dot_config" ]; then
            project_code=$(grep "^code = " "$dot_config" | cut -d"=" -f2 | tr -d " \"")
            if [ -n "$project_code" ]; then
                worktree="${project_code}-${ticket_number}"
            else
                worktree="${ticket_number}"
            fi
        else
            worktree="${ticket_number}"
        fi
    fi

    assert_equal "$worktree" "123"
}

@test "preserves: existing prefix when already provided" {
    # Given: input with project prefix (e.g., "MDT-123")
    # When: worktree name is constructed
    # Then: should not add another prefix

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    create_mdt_config "$TEST_REPO_DIR" "TEST"

    # Input already has prefix
    worktree="MDT-123"
    ticket_number=$(echo "$worktree" | grep -Eo "[0-9][0-9][0-9]")

    # Should NOT match the plain 3-digit pattern, so won't add prefix
    if [[ "$worktree" =~ ^[0-9][0-9][0-9]$ ]]; then
        fail "Should not modify already-prefixed worktree name"
    fi

    assert_equal "$worktree" "MDT-123"
}

@test "handles: empty project code in config" {
    # Given: .mdt-config.toml with empty code field
    # When: input is plain 3-digit number
    # Then: should fall back to plain ticket number

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    # Create config with empty code
    cat >"$TEST_REPO_DIR/.mdt-config.toml" <<EOF
[project]
code = ""
EOF

    worktree="123"
    ticket_number=$(echo "$worktree" | grep -Eo "[0-9][0-9][0-9]")
    dot_config="$(git_test rev-parse --show-toplevel)/.mdt-config.toml"

    if [[ "$worktree" =~ ^[0-9][0-9][0-9]$ ]]; then
        if [ -f "$dot_config" ]; then
            project_code=$(grep "^code = " "$dot_config" | cut -d"=" -f2 | tr -d " \"")
            if [ -n "$project_code" ]; then
                worktree="${project_code}-${ticket_number}"
            else
                worktree="${ticket_number}"
            fi
        fi
    fi

    assert_equal "$worktree" "123"
}

@test "extracts: correct code format from config" {
    # Given: .mdt-config.toml with various code formats
    # When: parsing the code field
    # Then: should handle quoted and unquoted values

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    # Test with double quotes
    cat >"$TEST_REPO_DIR/.mdt-config.toml" <<EOF
[project]
code = "WTA"
EOF

    dot_config="$(git_test rev-parse --show-toplevel)/.mdt-config.toml"
    project_code=$(grep "^code = " "$dot_config" | cut -d"=" -f2 | tr -d " \"")

    assert_equal "$project_code" "WTA"

    # Test with single quotes
    cat >"$TEST_REPO_DIR/.mdt-config.toml" <<EOF
[project]
code = 'MDT'
EOF

    project_code=$(grep "^code = " "$dot_config" | cut -d"=" -f2 | tr -d " '")

    assert_equal "$project_code" "MDT"
}
