#!/usr/bin/env bats
#
# Tests for: WTA - Worktree Removal (git wt-rm)
# Feature: Safe removal of worktrees with path discovery
# Requirements: Derived from git_config_alias_worktree.sh
# Generated by: /mdt:tests
# Status: GREEN (calls actual git wt-rm alias)
#

setup() {
    load 'test_helper/common-setup.bash'
    _common_setup

    # Create a shared test repo for all tests in this file
    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1
}

teardown() {
    if [[ -n "$TEST_REPO_DIR" && -d "$TEST_REPO_DIR" ]]; then
        cleanup_test_repo "$TEST_REPO_DIR"
    fi
    _common_teardown
}

# Feature: wt-rm Ticket Validation

@test "wt-rm: validates 3-digit ticket number" {
    # Given: git wt-rm command
    # When: executed with non-numeric input
    # Then: should exit with code 3 and show error

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.defaultPath ".gitWT/{worktree_name}"

    # Call actual git wt-rm command with invalid input
    run git_test wt-rm abc 2>&1 || true

    assert_failure
    assert_output --partial "Must include 3-digit ticket number"
}

@test "wt-rm: extracts ticket number from input" {
    # Given: various input formats
    # When: extracting ticket number
    # Then: should correctly extract 3 digits

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.defaultPath ".gitWT/{worktree_name}"

    # Create a worktree first with plain number
    run git_test wt 123 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-123" ]

    # Test removal with plain number
    WT_TEST_RESPONSE="y" run git_test wt-rm 123 2>&1 || true
    assert_output --partial "WTA-123"

    # Create another worktree with prefixed format
    run git_test wt 456 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-456" ]

    # Test removal with prefixed format
    WT_TEST_RESPONSE="y" run git_test wt-rm WTA-456 2>&1 || true
    assert_output --partial "WTA-456"
}

# Feature: wt-rm Path Resolution

@test "wt-rm: uses same path resolution as git wt" {
    # Given: worktree.defaultPath configuration
    # When: resolving worktree path for removal
    # Then: should use same logic as git wt

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.defaultPath ".gitWT/{worktree_name}"

    # Create worktree first
    run git_test wt 123 2>&1 || true

    # Remove worktree with WT_TEST_RESPONSE for automated confirmation
    WT_TEST_RESPONSE="y" run git_test wt-rm 123 2>&1 || true

    # Verify it found and removed the correct path
    assert_output --partial ".gitWT/WTA-123"
    assert_output --partial "Removed worktree"
}

@test "wt-rm: handles absolute paths" {
    # Given: absolute worktree.defaultPath
    # When: resolving path for removal
    # Then: should find worktree at absolute path

    TEST_WORKTREE_BASE=$(mktemp -d)
    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.defaultPath "$TEST_WORKTREE_BASE/{worktree_name}"

    # Create worktree at absolute path
    run git_test wt 789 2>&1 || true
    [ -d "$TEST_WORKTREE_BASE/WTA-789" ]

    # Remove worktree with WT_TEST_RESPONSE for automated confirmation
    WT_TEST_RESPONSE="y" run git_test wt-rm 789 2>&1 || true

    # Verify it found and removed the correct absolute path
    assert_output --partial "$TEST_WORKTREE_BASE/WTA-789"
    assert_output --partial "Removed worktree"

    # Cleanup the worktree base directory
    rmdir "$TEST_WORKTREE_BASE" 2>/dev/null || true
}

# Feature: wt-rm Error Handling

@test "wt-rm: errors when worktree not found" {
    # Given: no existing worktree at resolved path
    # When: attempting removal
    # Then: should exit with error code 1

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.defaultPath ".gitWT/{worktree_name}"

    # Try to remove non-existent worktree
    WT_TEST_RESPONSE="y" run git_test wt-rm 999 2>&1 || true

    assert_failure
    assert_output --partial "Worktree not found"
}

@test "wt-rm: lists existing worktrees on error" {
    # Given: worktree not found
    # When: showing error message
    # Then: should include 'git worktree list' output

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.defaultPath ".gitWT/{worktree_name}"

    # Create a worktree first so there's something to list
    run git_test wt 111 2>&1 || true

    # Try to remove non-existent worktree (should list existing ones)
    WT_TEST_RESPONSE="y" run git_test wt-rm 999 2>&1 || true

    assert_output --partial "Worktree not found"
    assert_output --partial "existing worktrees"

    # Cleanup the created worktree
    if [ -d "$TEST_REPO_DIR/.gitWT/WTA-111" ]; then
        git_test worktree remove "$TEST_REPO_DIR/.gitWT/WTA-111" 2>/dev/null || true
    fi
}

@test "wt-rm: uses default path when config missing" {
    # Given: no worktree.defaultPath configured
    # When: resolving path
    # Then: should use fallback .gitWT/{worktree_name}

    create_mdt_config "$TEST_REPO_DIR" "WTA"

    # Clear config
    git_test config --unset worktree.defaultPath 2>/dev/null || true
    git_test config --global --unset worktree.defaultPath 2>/dev/null || true

    # Create worktree - should use default path
    run git_test wt 222 2>&1 || true

    # Verify it used the default path
    [ -d "$TEST_REPO_DIR/.gitWT/222" ] || [ -d "$TEST_REPO_DIR/.gitWT/WTA-222" ]

    # Cleanup
    if [ -d "$TEST_REPO_DIR/.gitWT/222" ]; then
        git_test worktree remove "$TEST_REPO_DIR/.gitWT/222" 2>/dev/null || true
    fi
    if [ -d "$TEST_REPO_DIR/.gitWT/WTA-222" ]; then
        git_test worktree remove "$TEST_REPO_DIR/.gitWT/WTA-222" 2>/dev/null || true
    fi
}

@test "wt-rm: cancels removal when response is no" {
    # Given: an existing worktree
    # When: user responds 'n' to confirmation prompt
    # Then: should cancel removal

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.defaultPath ".gitWT/{worktree_name}"

    # Create worktree
    run git_test wt 333 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-333" ]

    # Try to remove with 'n' response
    WT_TEST_RESPONSE="n" run git_test wt-rm 333 2>&1 || true

    assert_output --partial "Cancelled"

    # Verify worktree still exists
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-333" ]

    # Cleanup
    git_test worktree remove "$TEST_REPO_DIR/.gitWT/WTA-333" 2>/dev/null || true
}
