#!/usr/bin/env bats
#
# Tests for: WTA-003 - Merge Protection and Auto-Merge Capability
# Feature: Detect unmerged commits, provide merge options, automation support
# Requirements: WTA-003 requirements.md
# Generated by: /mdt:tests
# Status: RED (implementation pending)
#

setup() {
    load 'test_helper/common-setup.bash'
    _common_setup

    # Create a shared test repo for all tests in this file
    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1
}

teardown() {
    if [[ -n "$TEST_REPO_DIR" && -d "$TEST_REPO_DIR" ]]; then
        cleanup_test_repo "$TEST_REPO_DIR"
    fi
    _common_teardown
}

# ============================================================================
# Feature: Unmerged Commit Detection (Requirement 1)
# ============================================================================

@test "wt-rm: detects unmerged commits before deletion" {
    # Given: a worktree with unmerged commits
    # When: wt-rm is executed without merge flags
    # Then: should detect unmerged commits and prompt user

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create worktree
    run git_test wt 101 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-101" ]

    # Add unmerged commit to the branch
    cd "$TEST_REPO_DIR/.gitWT/WTA-101" || return 1
    echo "unmerged work" > unmerged.txt
    git_test add unmerged.txt
    git_test commit -m "Unmerged commit"
    cd "$TEST_REPO_DIR" || return 1

    # Attempt to remove - should detect unmerged and prompt
    WT_TEST_RESPONSE="n" run git_test wt-rm 101 2>&1 || true

    # Should show prompt about unmerged commits
    assert_output --partial "unmerged commits"
    assert_output --partial "Merge"

    # Worktree and branch should be preserved (user said no)
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-101" ]
    git_test show-ref --verify --quiet "refs/heads/WTA-101"

    # Cleanup
    git_test worktree remove "$TEST_REPO_DIR/.gitWT/WTA-101" 2>/dev/null || true
    git_test branch -D WTA-101 2>/dev/null || true
}

@test "wt-rm: proceeds with deletion when no unmerged commits" {
    # Given: a worktree with fully merged commits
    # When: wt-rm is executed
    # Then: should proceed with deletion without merge prompt

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create worktree
    run git_test wt 102 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-102" ]

    # Add commit and merge it to main
    cd "$TEST_REPO_DIR/.gitWT/WTA-102" || return 1
    echo "merged work" > merged.txt
    git_test add merged.txt
    git_test commit -m "Merged commit"
    cd "$TEST_REPO_DIR" || return 1

    # Merge branch to main (making it fully merged)
    git_test merge WTA-102 --no-edit

    # Remove - should NOT prompt about merge
    WT_TEST_RESPONSE="y" run git_test wt-rm 102 2>&1 || true

    # Should NOT show unmerged commit prompt
    refute_output --partial "unmerged commits"
    refute_output --partial "Merge"

    # Should successfully remove
    assert_output --partial "Removed worktree"

    # Verify worktree and branch are removed
    [ ! -d "$TEST_REPO_DIR/.gitWT/WTA-102" ]
    run git_test show-ref --verify --quiet "refs/heads/WTA-102" 2>&1 || true
    assert_failure
}

# ============================================================================
# Feature: Interactive Merge Prompt (Requirement 2)
# ============================================================================

@test "wt-rm: merges when user responds yes to prompt" {
    # Given: unmerged commits detected
    # When: user responds 'y' or 'yes'
    # Then: should execute merge and delete branch

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create worktree
    run git_test wt 103 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-103" ]

    # Add unmerged commit
    cd "$TEST_REPO_DIR/.gitWT/WTA-103" || return 1
    echo "work to merge" > work.txt
    git_test add work.txt
    git_test commit -m "Work to merge"
    cd "$TEST_REPO_DIR" || return 1

    # Remove with 'yes' response
    WT_TEST_RESPONSE="yes" run git_test wt-rm 103 2>&1 || true

    # Should show merge prompt
    assert_output --partial "Merge"

    # Should execute merge
    assert_output --partial "merging"

    # Should successfully remove worktree and branch
    assert_output --partial "Removed worktree"
    [ ! -d "$TEST_REPO_DIR/.gitWT/WTA-103" ]
    run git_test show-ref --verify --quiet "refs/heads/WTA-103" 2>&1 || true
    assert_failure

    # Verify merge actually happened
    git_test log --oneline --all | grep "Work to merge"
}

@test "wt-rm: preserves branch when user responds no to prompt" {
    # Given: unmerged commits detected
    # When: user responds 'n' or 'no'
    # Then: should preserve branch and worktree

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create worktree
    run git_test wt 104 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-104" ]

    # Add unmerged commit
    cd "$TEST_REPO_DIR/.gitWT/WTA-104" || return 1
    echo "keep this work" > keep.txt
    git_test add keep.txt
    git_test commit -m "Work to keep"
    cd "$TEST_REPO_DIR" || return 1

    # Remove with 'no' response
    WT_TEST_RESPONSE="no" run git_test wt-rm 104 2>&1 || true

    # Should show merge prompt
    assert_output --partial "Merge"

    # Should cancel operation
    assert_output --partial "Cancelled"

    # Verify worktree and branch are preserved
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-104" ]
    git_test show-ref --verify --quiet "refs/heads/WTA-104"

    # Cleanup
    git_test worktree remove "$TEST_REPO_DIR/.gitWT/WTA-104" 2>/dev/null || true
    git_test branch -D WTA-104 2>/dev/null || true
}

@test "wt-rm: respects WT_TEST_RESPONSE environment variable" {
    # Given: unmerged commits detected
    # When: WT_TEST_RESPONSE is set
    # Then: should use response from variable instead of prompting

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create worktree
    run git_test wt 105 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-105" ]

    # Add unmerged commit
    cd "$TEST_REPO_DIR/.gitWT/WTA-105" || return 1
    echo "automated merge" > auto.txt
    git_test add auto.txt
    git_test commit -m "Automated merge test"
    cd "$TEST_REPO_DIR" || return 1

    # Use WT_TEST_RESPONSE for automation
    WT_TEST_RESPONSE="y" run git_test wt-rm 105 2>&1 || true

    # Should successfully merge and remove
    assert_output --partial "merging"
    assert_output --partial "Removed worktree"
    [ ! -d "$TEST_REPO_DIR/.gitWT/WTA-105" ]
}

@test "wt-rm: accepts case-insensitive yes responses" {
    # Given: unmerged commits detected
    # When: user responds with Y, YES, Yes, y, yes
    # Then: should accept all variants as yes

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Test uppercase Y
    run git_test wt 106 2>&1 || true
    cd "$TEST_REPO_DIR/.gitWT/WTA-106" || return 1
    echo "test Y" > test.txt
    git_test add test.txt
    git_test commit -m "Test Y"
    cd "$TEST_REPO_DIR" || return 1
    WT_TEST_RESPONSE="Y" run git_test wt-rm 106 2>&1 || true
    assert_output --partial "merging"
    git_test branch -D WTA-106 2>/dev/null || true

    # Test mixed case Yes
    run git_test wt 107 2>&1 || true
    cd "$TEST_REPO_DIR/.gitWT/WTA-107" || return 1
    echo "test Yes" > test.txt
    git_test add test.txt
    git_test commit -m "Test Yes"
    cd "$TEST_REPO_DIR" || return 1
    WT_TEST_RESPONSE="Yes" run git_test wt-rm 107 2>&1 || true
    assert_output --partial "merging"
    git_test branch -D WTA-107 2>/dev/null || true
}

# ============================================================================
# Feature: Explicit Merge Flag (Requirement 3)
# ============================================================================

@test "wt-rm: merges without prompt when --merge flag provided" {
    # Given: unmerged commits exist
    # When: --merge flag is provided
    # Then: should merge into current branch without prompting

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create worktree
    run git_test wt 108 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-108" ]

    # Add unmerged commit
    cd "$TEST_REPO_DIR/.gitWT/WTA-108" || return 1
    echo "explicit merge" > explicit.txt
    git_test add explicit.txt
    git_test commit -m "Explicit merge test"
    cd "$TEST_REPO_DIR" || return 1

    # Remove with --merge flag (no prompt)
    WT_TEST_RESPONSE="y" run git_test wt-rm --merge 108 2>&1 || true

    # Should NOT show merge prompt
    refute_output --partial "Merge unmerged commits"

    # Should execute merge
    assert_output --partial "merging"

    # Should successfully remove
    assert_output --partial "Removed worktree"
    [ ! -d "$TEST_REPO_DIR/.gitWT/WTA-108" ]
}

@test "wt-rm: preserves worktree on merge conflict with --merge flag" {
    # Given: unmerged commits that will conflict
    # When: --merge flag is provided and merge conflicts
    # Then: should preserve worktree and branch, exit with error code 2

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create worktree
    run git_test wt 109 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-109" ]

    # Create conflicting change in main
    echo "conflict in main" > conflict.txt
    git_test add conflict.txt
    git_test commit -m "Conflict in main"

    # Create conflicting change in worktree
    cd "$TEST_REPO_DIR/.gitWT/WTA-109" || return 1
    echo "conflict in worktree" > conflict.txt
    git_test add conflict.txt
    git_test commit -m "Conflict in worktree"
    cd "$TEST_REPO_DIR" || return 1

    # Attempt to remove with --merge
    run git_test wt-rm --merge 109 2>&1 || true

    # Should exit with error code 2 (merge failure)
    assert_equal "$status" 2

    # Should show error about merge conflict
    assert_output --partial "conflict"

    # Should preserve worktree and branch
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-109" ]
    git_test show-ref --verify --quiet "refs/heads/WTA-109"

    # Cleanup
    git_test merge --abort 2>/dev/null || true
    git_test worktree remove "$TEST_REPO_DIR/.gitWT/WTA-109" 2>/dev/null || true
    git_test branch -D WTA-109 2>/dev/null || true
}

@test "wt-rm: exits with code 2 on merge failure" {
    # Given: merge operation fails
    # When: --merge flag is provided
    # Then: should exit with error code 2

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create worktree
    run git_test wt 110 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-110" ]

    # Create conflicting change
    cd "$TEST_REPO_DIR/.gitWT/WTA-110" || return 1
    echo "conflict" > conflict.txt
    git_test add conflict.txt
    git_test commit -m "Conflict"
    cd "$TEST_REPO_DIR" || return 1

    # Create same file with different content in main
    echo "different" > conflict.txt
    git_test add conflict.txt
    git_test commit -m "Different content"

    # Attempt merge
    run git_test wt-rm --merge 110 2>&1 || true

    # Exit code should be 2
    assert_equal "$status" 2

    # Cleanup
    git_test merge --abort 2>/dev/null || true
    git_test worktree remove "$TEST_REPO_DIR/.gitWT/WTA-110" 2>/dev/null || true
    git_test branch -D WTA-110 2>/dev/null || true
}

# ============================================================================
# Feature: Explicit Target Merge Flag (Requirement 4)
# ============================================================================

@test "wt-rm: merges to explicit target branch with --merge-to" {
    # Given: unmerged commits exist
    # When: --merge-to TARGET flag is provided
    # Then: should switch to target, merge, switch back, and delete

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create worktree from main
    run git_test wt 111 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-111" ]

    # Add unmerged commit
    cd "$TEST_REPO_DIR/.gitWT/WTA-111" || return 1
    echo "target merge" > target.txt
    git_test add target.txt
    git_test commit -m "Target merge test"
    cd "$TEST_REPO_DIR" || return 1

    # Get current branch (should be main)
    local current_branch=$(git_test branch --show-current)

    # Remove with --merge-to main
    WT_TEST_RESPONSE="y" run git_test wt-rm --merge-to main 111 2>&1 || true

    # Should execute merge
    assert_output --partial "merging"

    # Should successfully remove
    assert_output --partial "Removed worktree"
    [ ! -d "$TEST_REPO_DIR/.gitWT/WTA-111" ]

    # Verify we're back on original branch
    local final_branch=$(git_test branch --show-current)
    assert_equal "$current_branch" "$final_branch"

    # Verify merge happened in main
    git_test log --oneline --all | grep "Target merge test"
}

@test "wt-rm: skips branch switch when already on target" {
    # Given: already on target branch
    # When: --merge-to current_branch flag is provided
    # Then: should merge without switching branches

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Get current branch
    local current_branch=$(git_test branch --show-current)

    # Create worktree
    run git_test wt 112 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-112" ]

    # Add unmerged commit
    cd "$TEST_REPO_DIR/.gitWT/WTA-112" || return 1
    echo "already on target" > target.txt
    git_test add target.txt
    git_test commit -m "Already on target"
    cd "$TEST_REPO_DIR" || return 1

    # Remove with --merge-to to current branch
    WT_TEST_RESPONSE="y" run git_test wt-rm --merge-to "$current_branch" 112 2>&1 || true

    # Should merge successfully
    assert_output --partial "merging"
    assert_output --partial "Removed worktree"
    [ ! -d "$TEST_REPO_DIR/.gitWT/WTA-112" ]
}

@test "wt-rm: errors when target branch does not exist" {
    # Given: unmerged commits exist
    # When: --merge-to specifies non-existent target
    # Then: should exit with error code 1 and show error

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create worktree
    run git_test wt 113 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-113" ]

    # Add unmerged commit
    cd "$TEST_REPO_DIR/.gitWT/WTA-113" || return 1
    echo "target not found" > target.txt
    git_test add target.txt
    git_test commit -m "Target not found test"
    cd "$TEST_REPO_DIR" || return 1

    # Attempt to remove with non-existent target
    run git_test wt-rm --merge-to nonexistent-branch 113 2>&1 || true

    # Should exit with error code 1
    assert_equal "$status" 1

    # Should show error about target not found
    assert_output --partial "not found"

    # Should preserve worktree and branch
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-113" ]
    git_test show-ref --verify --quiet "refs/heads/WTA-113"

    # Cleanup
    git_test worktree remove "$TEST_REPO_DIR/.gitWT/WTA-113" 2>/dev/null || true
    git_test branch -D WTA-113 2>/dev/null || true
}

# ============================================================================
# Feature: Auto-Merge Configuration (Requirement 5)
# ============================================================================

@test "wt-rm: auto-merges when config is true" {
    # Given: autoMerge config is set to true
    # When: unmerged commits are detected
    # Then: should merge automatically without prompting

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"
    git_test config worktree.wt.autoMerge true

    # Create worktree
    run git_test wt 114 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-114" ]

    # Add unmerged commit
    cd "$TEST_REPO_DIR/.gitWT/WTA-114" || return 1
    echo "auto merge" > auto.txt
    git_test add auto.txt
    git_test commit -m "Auto merge test"
    cd "$TEST_REPO_DIR" || return 1

    # Remove without flags - should auto-merge
    WT_TEST_RESPONSE="y" run git_test wt-rm 114 2>&1 || true

    # Should NOT prompt
    refute_output --partial "Merge unmerged commits"

    # Should execute merge
    assert_output --partial "merging"

    # Should successfully remove
    assert_output --partial "Removed worktree"
    [ ! -d "$TEST_REPO_DIR/.gitWT/WTA-114" ]
}

@test "wt-rm: auto-merges when config is 'on'" {
    # Given: autoMerge config is set to 'on'
    # When: unmerged commits are detected
    # Then: should merge automatically

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"
    git_test config worktree.wt.autoMerge on

    # Create worktree
    run git_test wt 115 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-115" ]

    # Add unmerged commit
    cd "$TEST_REPO_DIR/.gitWT/WTA-115" || return 1
    echo "auto merge on" > auto.txt
    git_test add auto.txt
    git_test commit -m "Auto merge on"
    cd "$TEST_REPO_DIR" || return 1

    # Remove - should auto-merge
    WT_TEST_RESPONSE="y" run git_test wt-rm 115 2>&1 || true
    assert_output --partial "merging"
    [ ! -d "$TEST_REPO_DIR/.gitWT/WTA-115" ]
}

@test "wt-rm: auto-merges when config is 'yes'" {
    # Given: autoMerge config is set to 'yes'
    # When: unmerged commits are detected
    # Then: should merge automatically

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"
    git_test config worktree.wt.autoMerge yes

    # Create worktree
    run git_test wt 116 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-116" ]

    # Add unmerged commit
    cd "$TEST_REPO_DIR/.gitWT/WTA-116" || return 1
    echo "auto merge yes" > auto.txt
    git_test add auto.txt
    git_test commit -m "Auto merge yes"
    cd "$TEST_REPO_DIR" || return 1

    # Remove - should auto-merge
    WT_TEST_RESPONSE="y" run git_test wt-rm 116 2>&1 || true
    assert_output --partial "merging"
    [ ! -d "$TEST_REPO_DIR/.gitWT/WTA-116" ]
}

@test "wt-rm: auto-merges when config is '1'" {
    # Given: autoMerge config is set to '1'
    # When: unmerged commits are detected
    # Then: should merge automatically

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"
    git_test config worktree.wt.autoMerge 1

    # Create worktree
    run git_test wt 117 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-117" ]

    # Add unmerged commit
    cd "$TEST_REPO_DIR/.gitWT/WTA-117" || return 1
    echo "auto merge 1" > auto.txt
    git_test add auto.txt
    git_test commit -m "Auto merge 1"
    cd "$TEST_REPO_DIR" || return 1

    # Remove - should auto-merge
    WT_TEST_RESPONSE="y" run git_test wt-rm 117 2>&1 || true
    assert_output --partial "merging"
    [ ! -d "$TEST_REPO_DIR/.gitWT/WTA-117" ]
}

@test "wt-rm: prompts when autoMerge config is false" {
    # Given: autoMerge config is set to false
    # When: unmerged commits are detected
    # Then: should prompt user (not auto-merge)

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"
    git_test config worktree.wt.autoMerge false

    # Create worktree
    run git_test wt 118 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-118" ]

    # Add unmerged commit
    cd "$TEST_REPO_DIR/.gitWT/WTA-118" || return 1
    echo "no auto merge" > noauto.txt
    git_test add noauto.txt
    git_test commit -m "No auto merge"
    cd "$TEST_REPO_DIR" || return 1

    # Remove - should prompt (not auto-merge)
    WT_TEST_RESPONSE="n" run git_test wt-rm 118 2>&1 || true

    # Should show prompt
    assert_output --partial "Merge"

    # Should NOT auto-merge
    refute_output --partial "merging"

    # Cleanup
    git_test worktree remove "$TEST_REPO_DIR/.gitWT/WTA-118" 2>/dev/null || true
    git_test branch -D WTA-118 2>/dev/null || true
}

@test "wt-rm: flags override autoMerge config" {
    # Given: autoMerge config is true
    # When: --delete-unmerged flag is provided
    # Then: flag should override config and delete without merging

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"
    git_test config worktree.wt.autoMerge true

    # Create worktree
    run git_test wt 119 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-119" ]

    # Add unmerged commit
    cd "$TEST_REPO_DIR/.gitWT/WTA-119" || return 1
    echo "flag override" > override.txt
    git_test add override.txt
    git_test commit -m "Flag override"
    cd "$TEST_REPO_DIR" || return 1

    # Remove with --delete-unmerged - should skip merge
    WT_TEST_RESPONSE="y" run git_test wt-rm --delete-unmerged 119 2>&1 || true

    # Should NOT merge
    refute_output --partial "merging"

    # Should delete
    assert_output --partial "Removed worktree"
    [ ! -d "$TEST_REPO_DIR/.gitWT/WTA-119" ]
}

# ============================================================================
# Feature: Force Delete Flag (Requirement 6)
# ============================================================================

@test "wt-rm: deletes unmerged branch with --delete-unmerged flag" {
    # Given: unmerged commits exist
    # When: --delete-unmerged flag is provided
    # Then: should delete branch without merging

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create worktree
    run git_test wt 120 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-120" ]

    # Add unmerged commit
    cd "$TEST_REPO_DIR/.gitWT/WTA-120" || return 1
    echo "force delete" > force.txt
    git_test add force.txt
    git_test commit -m "Force delete test"
    cd "$TEST_REPO_DIR" || return 1

    # Remove with --delete-unmerged
    WT_TEST_RESPONSE="y" run git_test wt-rm --delete-unmerged 120 2>&1 || true

    # Should NOT merge
    refute_output --partial "merging"

    # Should delete worktree and branch
    assert_output --partial "Removed worktree"
    [ ! -d "$TEST_REPO_DIR/.gitWT/WTA-120" ]
    run git_test show-ref --verify --quiet "refs/heads/WTA-120" 2>&1 || true
    assert_failure
}

@test "wt-rm: skips merge prompts with --delete-unmerged flag" {
    # Given: unmerged commits exist
    # When: --delete-unmerged flag is provided
    # Then: should skip merge prompts entirely

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create worktree
    run git_test wt 121 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-121" ]

    # Add unmerged commit
    cd "$TEST_REPO_DIR/.gitWT/WTA-121" || return 1
    echo "skip prompt" > skip.txt
    git_test add skip.txt
    git_test commit -m "Skip prompt"
    cd "$TEST_REPO_DIR" || return 1

    # Remove with --delete-unmerged
    WT_TEST_RESPONSE="y" run git_test wt-rm --delete-unmerged 121 2>&1 || true

    # Should NOT show merge prompt
    refute_output --partial "Merge unmerged commits"

    # Should delete
    assert_output --partial "Removed worktree"
    [ ! -d "$TEST_REPO_DIR/.gitWT/WTA-121" ]
}

# ============================================================================
# Feature: Quiet Mode Flag (Requirement 7)
# ============================================================================

@test "wt-rm: auto-merges in quiet mode when config is true" {
    # Given: autoMerge config is true
    # When: --quiet flag is provided
    # Then: should auto-merge without prompts

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"
    git_test config worktree.wt.autoMerge true

    # Create worktree
    run git_test wt 122 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-122" ]

    # Add unmerged commit
    cd "$TEST_REPO_DIR/.gitWT/WTA-122" || return 1
    echo "quiet auto merge" > quiet.txt
    git_test add quiet.txt
    git_test commit -m "Quiet auto merge"
    cd "$TEST_REPO_DIR" || return 1

    # Remove with --quiet
    WT_TEST_RESPONSE="y" run git_test wt-rm --quiet 122 2>&1 || true

    # Should NOT prompt
    refute_output --partial "Merge unmerged commits"

    # Should merge
    assert_output --partial "merging"
    [ ! -d "$TEST_REPO_DIR/.gitWT/WTA-122" ]
}

@test "wt-rm: fails in quiet mode when autoMerge is false" {
    # Given: autoMerge config is false
    # When: --quiet flag is provided and unmerged commits exist
    # Then: should fail without prompting

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"
    git_test config worktree.wt.autoMerge false

    # Create worktree
    run git_test wt 123 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-123" ]

    # Add unmerged commit
    cd "$TEST_REPO_DIR/.gitWT/WTA-123" || return 1
    echo "quiet fail" > quiet.txt
    git_test add quiet.txt
    git_test commit -m "Quiet fail"
    cd "$TEST_REPO_DIR" || return 1

    # Remove with --quiet - should fail
    run git_test wt-rm --quiet 123 2>&1 || true

    # Should fail
    assert_failure

    # Should NOT prompt
    refute_output --partial "Merge unmerged commits"

    # Should preserve worktree and branch
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-123" ]
    git_test show-ref --verify --quiet "refs/heads/WTA-123"

    # Cleanup
    git_test worktree remove "$TEST_REPO_DIR/.gitWT/WTA-123" 2>/dev/null || true
    git_test branch -D WTA-123 2>/dev/null || true
}

@test "wt-rm: skips all prompts in quiet mode" {
    # Given: any prompts would be shown
    # When: --quiet flag is provided
    # Then: should skip all interactive prompts

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create worktree with merged commits
    run git_test wt 124 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-124" ]

    cd "$TEST_REPO_DIR/.gitWT/WTA-124" || return 1
    echo "quiet no prompt" > quiet.txt
    git_test add quiet.txt
    git_test commit -m "Quiet no prompt"
    cd "$TEST_REPO_DIR" || return 1
    git_test merge WTA-124 --no-edit

    # Remove with --quiet
    run git_test wt-rm --quiet 124 2>&1 || true

    # Should NOT show any prompts
    refute_output --partial "Remove worktree"
    refute_output --partial "Delete branch"

    # Should remove
    [ ! -d "$TEST_REPO_DIR/.gitWT/WTA-124" ]
}

# ============================================================================
# Feature: Flag Conflict Detection (Requirement 8)
# ============================================================================

@test "wt-rm: errors on --merge and --merge-to conflict" {
    # Given: conflicting merge flags
    # When: both --merge and --merge-to are provided
    # Then: should exit with error code 3

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Attempt to remove with conflicting flags
    run git_test wt-rm --merge --merge-to main 125 2>&1 || true

    # Should exit with error code 3
    assert_equal "$status" 3

    # Should show error about conflicting flags
    assert_output --partial "Conflicting flags"
}

@test "wt-rm: errors on --merge and --delete-unmerged conflict" {
    # Given: conflicting intent flags
    # When: both --merge and --delete-unmerged are provided
    # Then: should exit with error code 3

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create worktree
    run git_test wt 126 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-126" ]

    # Attempt to remove with conflicting flags
    run git_test wt-rm --merge --delete-unmerged 126 2>&1 || true

    # Should exit with error code 3
    assert_equal "$status" 3

    # Should show error about conflicting flags
    assert_output --partial "Conflicting flags"

    # Cleanup
    git_test worktree remove "$TEST_REPO_DIR/.gitWT/WTA-126" 2>/dev/null || true
    git_test branch -D WTA-126 2>/dev/null || true
}

@test "wt-rm: errors on --merge-to and --delete-unmerged conflict" {
    # Given: conflicting intent flags
    # When: both --merge-to and --delete-unmerged are provided
    # Then: should exit with error code 3

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create worktree
    run git_test wt 127 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-127" ]

    # Attempt to remove with conflicting flags
    run git_test wt-rm --merge-to main --delete-unmerged 127 2>&1 || true

    # Should exit with error code 3
    assert_equal "$status" 3

    # Should show error about conflicting flags
    assert_output --partial "Conflicting flags"

    # Cleanup
    git_test worktree remove "$TEST_REPO_DIR/.gitWT/WTA-127" 2>/dev/null || true
    git_test branch -D WTA-127 2>/dev/null || true
}

# ============================================================================
# Feature: Error Handling and Edge Cases (Requirement 9)
# ============================================================================

@test "wt-rm: errors when removing current worktree" {
    # Given: user is currently in the worktree being removed
    # When: wt-rm is executed
    # Then: should exit with error code 1 and show error

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create worktree
    run git_test wt 128 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-128" ]

    # Add unmerged commit
    cd "$TEST_REPO_DIR/.gitWT/WTA-128" || return 1
    echo "current worktree" > current.txt
    git_test add current.txt
    git_test commit -m "Current worktree test"

    # Attempt to remove while inside worktree
    run git_test wt-rm --delete-unmerged 128 2>&1 || true

    # Should exit with error code 1
    assert_equal "$status" 1

    # Should show error about current worktree
    assert_output --partial "Cannot remove current worktree"

    # Worktree should be preserved
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-128" ]

    # Cleanup
    cd "$TEST_REPO_DIR" || return 1
    git_test worktree remove "$TEST_REPO_DIR/.gitWT/WTA-128" 2>/dev/null || true
    git_test branch -D WTA-128 2>/dev/null || true
}

@test "wt-rm: preserves worktree on merge conflict" {
    # Given: merge operation conflicts
    # When: merge is attempted
    # Then: should preserve worktree and branch in current state

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create worktree
    run git_test wt 129 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-129" ]

    # Create conflicting change in worktree
    cd "$TEST_REPO_DIR/.gitWT/WTA-129" || return 1
    echo "conflict" > file.txt
    git_test add file.txt
    git_test commit -m "Conflict in worktree"
    cd "$TEST_REPO_DIR" || return 1

    # Create same file with different content in main
    echo "different" > file.txt
    git_test add file.txt
    git_test commit -m "Different in main"

    # Attempt merge
    run git_test wt-rm --merge 129 2>&1 || true

    # Should exit with error code 2
    assert_equal "$status" 2

    # Should preserve worktree
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-129" ]
    git_test show-ref --verify --quiet "refs/heads/WTA-129"

    # Cleanup
    git_test merge --abort 2>/dev/null || true
    cd "$TEST_REPO_DIR" || return 1
    git_test worktree remove "$TEST_REPO_DIR/.gitWT/WTA-129" 2>/dev/null || true
    git_test branch -D WTA-129 2>/dev/null || true
}

@test "wt-rm: removes worktree when branch already deleted" {
    # Given: worktree exists but branch is already deleted
    # When: wt-rm is executed
    # Then: should remove worktree only

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create worktree
    run git_test wt 130 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-130" ]

    # Manually delete branch
    git_test branch -D WTA-130 2>/dev/null || true

    # Verify branch is gone but worktree exists
    run git_test show-ref --verify --quiet "refs/heads/WTA-130" 2>&1 || true
    assert_failure
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-130" ]

    # Remove worktree - should work without branch
    WT_TEST_RESPONSE="y" run git_test wt-rm 130 2>&1 || true

    # Should remove worktree
    assert_output --partial "Removed worktree"
    [ ! -d "$TEST_REPO_DIR/.gitWT/WTA-130" ]
}

# ============================================================================
# Feature: Exit Codes (Requirement 10)
# ============================================================================

@test "wt-rm: exits with code 0 on successful removal" {
    # Given: valid worktree
    # When: wt-rm completes successfully
    # Then: should exit with code 0

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create worktree with merged commits
    run git_test wt 131 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-131" ]

    cd "$TEST_REPO_DIR/.gitWT/WTA-131" || return 1
    echo "success" > success.txt
    git_test add success.txt
    git_test commit -m "Success test"
    cd "$TEST_REPO_DIR" || return 1
    git_test merge WTA-131 --no-edit

    # Remove - should succeed
    WT_TEST_RESPONSE="y" run git_test wt-rm 131 2>&1 || true

    # Exit code should be 0
    assert_equal "$status" 0
}

@test "wt-rm: exits with code 1 on general error" {
    # Given: invalid worktree reference
    # When: wt-rm cannot find worktree
    # Then: should exit with code 1

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Try to remove non-existent worktree
    run git_test wt-rm 999 2>&1 || true

    # Exit code should be 1
    assert_equal "$status" 1
}

@test "wt-rm: exits with code 3 on invalid flag combination" {
    # Given: invalid flag combination
    # When: wt-rm is executed with conflicting flags
    # Then: should exit with code 3

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Try conflicting flags
    run git_test wt-rm --merge --delete-unmerged 132 2>&1 || true

    # Exit code should be 3
    assert_equal "$status" 3
}

# ============================================================================
# Feature: Backward Compatibility (Requirement 11)
# ============================================================================

@test "wt-rm: behaves identically to current implementation when no unmerged" {
    # Given: worktree with fully merged commits
    # When: wt-rm is executed without flags
    # Then: should behave identically to current implementation

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    # Create worktree
    run git_test wt 133 2>&1 || true
    [ -d "$TEST_REPO_DIR/.gitWT/WTA-133" ]

    # Add commit and merge it
    cd "$TEST_REPO_DIR/.gitWT/WTA-133" || return 1
    echo "backward compatible" > compat.txt
    git_test add compat.txt
    git_test commit -m "Backward compatible"
    cd "$TEST_REPO_DIR" || return 1
    git_test merge WTA-133 --no-edit

    # Remove - should follow existing workflow
    WT_TEST_RESPONSE="y" run git_test wt-rm 133 2>&1 || true

    # Should NOT show new merge prompts
    refute_output --partial "Merge unmerged commits"

    # Should use git branch -d (not -D)
    assert_output --partial "Deleted branch"

    # Should successfully remove
    assert_success
    [ ! -d "$TEST_REPO_DIR/.gitWT/WTA-133" ]
}
