#!/usr/bin/env bats
#
# Tests for: WTA - Ticket Validation
# Feature: git wt ticket number validation and extraction
# Requirements: Derived from git_config_alias_worktree.sh
# Generated by: /mdt:tests
# Status: GREEN (tests actual validation behavior)
#

setup() {
    load 'test_helper/common-setup.bash'
    _common_setup
}

teardown() {
    # Clean up any test repositories
    if [[ -n "$TEST_REPO_DIR" && -d "$TEST_REPO_DIR" ]]; then
        cleanup_test_repo "$TEST_REPO_DIR"
    fi
    _common_teardown
}

# Feature: Ticket Number Format Validation

@test "error: rejects input with 4-digit number" {
    # Given: git wt command
    # When: executed with 4-digit number (regex checks for 3 consecutive digits)
    # Then: should pass validation (contains 3-digit sequence)

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.defaultPath ".gitWT/{worktree_name}"

    # 4-digit contains 3-digit sequence, so should pass validation
    run git_test wt 1234 2>&1 || true

    # This should NOT produce the "Must include 3-digit" error
    # (though it may fail for other reasons like worktree already exists)
    if [[ "$output" == *"Must include 3-digit ticket number"* ]]; then
        echo "Should accept input containing 3 consecutive digits" >&2
        return 1
    fi
}

@test "accepts: 3-digit ticket number" {
    # Given: git wt command with valid 3-digit number
    # When: executed with "123"
    # Then: should not show format validation error

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.defaultPath ".gitWT/{worktree_name}"

    run git_test wt 123 2>&1 || true

    # Should not have the format validation error
    if [[ "$output" == *"Must include 3-digit ticket number"* ]]; then
        echo "Should accept 3-digit ticket number" >&2
        return 1
    fi

    # Cleanup if worktree was created
    if [ -d "$TEST_REPO_DIR/.gitWT/WTA-123" ]; then
        git_test worktree remove "$TEST_REPO_DIR/.gitWT/WTA-123" 2>/dev/null || true
    fi
}

@test "accepts: project-prefixed 3-digit ticket number" {
    # Given: git wt command with project prefix
    # When: executed with "MDT-123"
    # Then: should not show format validation error

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.defaultPath ".gitWT/{worktree_name}"

    run git_test wt MDT-123 2>&1 || true

    if [[ "$output" == *"Must include 3-digit ticket number"* ]]; then
        echo "Should accept project-prefixed ticket number" >&2
        return 1
    fi

    # Cleanup if worktree was created
    if [ -d "$TEST_REPO_DIR/.gitWT/MDT-123" ]; then
        git_test worktree remove "$TEST_REPO_DIR/.gitWT/MDT-123" 2>/dev/null || true
    fi
}

@test "extracts: ticket number from plain number (integration test)" {
    # Given: input "123"
    # When: creating worktree
    # Then: worktree should be created with correct ticket number

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    # Don't create .mdt-config.toml to test plain number behavior
    git_test config worktree.defaultPath ".gitWT/{worktree_name}"

    run git_test wt 123 2>&1 || true

    # Should create worktree with the plain ticket number (no prefix)
    assert_output --partial "123"

    # Cleanup if worktree was created
    if [ -d "$TEST_REPO_DIR/.gitWT/123" ]; then
        git_test worktree remove "$TEST_REPO_DIR/.gitWT/123" 2>/dev/null || true
    fi
}

@test "extracts: ticket number from prefixed format (integration test)" {
    # Given: input "MDT-123"
    # When: creating worktree
    # Then: worktree should be created preserving the prefix

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.defaultPath ".gitWT/{worktree_name}"

    run git_test wt MDT-123 2>&1 || true

    # Should create worktree with the full prefixed name
    assert_output --partial "MDT-123"

    # Cleanup if worktree was created
    if [ -d "$TEST_REPO_DIR/.gitWT/MDT-123" ]; then
        git_test worktree remove "$TEST_REPO_DIR/.gitWT/MDT-123" 2>/dev/null || true
    fi
}
