#!/usr/bin/env bats
#
# Tests for: WTA-002 - Zero-Padding Configuration
# Feature: Zero-padding configuration via git config
# Requirements: R2.1-R2.4, R4.1, R4.3 from WTA-002/requirements.md
# Generated by: /mdt:tests
# Status: RED (implementation pending)
#

setup() {
    load 'test_helper/common-setup.bash'
    _common_setup
}

teardown() {
    if [[ -n "$TEST_REPO_DIR" && -d "$TEST_REPO_DIR" ]]; then
        cleanup_test_repo "$TEST_REPO_DIR"
    fi
    _common_teardown
}

# Feature: Zero-Padding Configuration

@test "creates worktree with zero-padded ticket number" {
    # Given: repository with worktree.wt.zeroPadDigits configured to 3
    # And: worktree.wt.prefix configured to "WTA-"
    # When: user runs git wt 7
    # Then: branch named WTA-007 should exist

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    git_test config worktree.wt.prefix "WTA-"
    git_test config worktree.wt.zeroPadDigits 3
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    run git_test wt 7 2>&1

    git_test show-ref --verify --quiet "refs/heads/WTA-007"

    # Cleanup
    git_test worktree remove ".gitWT/WTA-007" 2>/dev/null || true
}

@test "creates worktree with 4-digit zero-padding" {
    # Given: repository with worktree.wt.zeroPadDigits configured to 4
    # And: worktree.wt.prefix configured to "PROJ-"
    # When: user runs git wt 12
    # Then: branch named PROJ-0012 should exist

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    git_test config worktree.wt.prefix "PROJ-"
    git_test config worktree.wt.zeroPadDigits 4
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    run git_test wt 12 2>&1

    git_test show-ref --verify --quiet "refs/heads/PROJ-0012"

    # Cleanup
    git_test worktree remove ".gitWT/PROJ-0012" 2>/dev/null || true
}

@test "creates worktree with zero-padded number without prefix" {
    # Given: repository with worktree.wt.zeroPadDigits configured to 3
    # And: no prefix configured
    # When: user runs git wt 5
    # Then: branch named 005 should exist

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    git_test config worktree.wt.zeroPadDigits 3
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    run git_test wt 5 2>&1

    git_test show-ref --verify --quiet "refs/heads/005"

    # Cleanup
    git_test worktree remove ".gitWT/005" 2>/dev/null || true
}

@test "creates worktree without zero-padding when not configured" {
    # Given: repository without worktree.wt.zeroPadDigits configured
    # And: worktree.wt.prefix configured to "PROJ-"
    # When: user runs git wt 42
    # Then: branch named PROJ-42 should exist (no padding)

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    git_test config worktree.wt.prefix "PROJ-"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    run git_test wt 42 2>&1

    git_test show-ref --verify --quiet "refs/heads/PROJ-42"

    # Cleanup
    git_test worktree remove ".gitWT/PROJ-42" 2>/dev/null || true
}

@test "does not truncate numbers larger than configured digit count" {
    # Given: repository with worktree.wt.zeroPadDigits configured to 3
    # When: user runs git wt 1234 (larger than 3 digits)
    # Then: branch with full number should exist (not truncated)

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    git_test config worktree.wt.prefix "PROJ-"
    git_test config worktree.wt.zeroPadDigits 3
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    run git_test wt 1234 2>&1

    git_test show-ref --verify --quiet "refs/heads/PROJ-1234"

    # Cleanup
    git_test worktree remove ".gitWT/PROJ-1234" 2>/dev/null || true
}

@test "MDT project auto-applies 3-digit zero-padding" {
    # Given: repository with .mdt-config.toml (code = "WTA")
    # And: no worktree.wt.zeroPadDigits configured
    # When: user runs git wt 12
    # Then: branch named WTA-012 should exist (auto 3-digit padding)

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    run git_test wt 12 2>&1

    git_test show-ref --verify --quiet "refs/heads/WTA-012"

    # Cleanup
    git_test worktree remove ".gitWT/WTA-012" 2>/dev/null || true
}

@test "git config zero-padding overrides MDT default" {
    # Given: repository with .mdt-config.toml (code = "WTA")
    # And: worktree.wt.zeroPadDigits configured to 4
    # When: user runs git wt 7
    # Then: branch named WTA-0007 should exist (4 digits, not 3)

    TEST_REPO_DIR=$(mktemp -d)
    create_test_repo "$TEST_REPO_DIR"
    cd "$TEST_REPO_DIR" || return 1

    create_mdt_config "$TEST_REPO_DIR" "WTA"
    git_test config worktree.wt.zeroPadDigits 4
    git_test config worktree.wt.defaultPath ".gitWT/{worktree_name}"

    run git_test wt 7 2>&1

    git_test show-ref --verify --quiet "refs/heads/WTA-0007"

    # Cleanup
    git_test worktree remove ".gitWT/WTA-0007" 2>/dev/null || true
}
